"""Constants for the Solem BL-IP integration."""

DOMAIN = "solem_blip"

DEFAULT_SCAN_INTERVAL = 60
MIN_SCAN_INTERVAL = 10
CONTROLLER_MAC_ADDRESS = "controller_mac_address"
NUM_STATIONS = "num_stations"

BLUETOOTH_TIMEOUT = "bluetooth_timeout"
BLUETOOTH_MIN_TIMEOUT = 5
BLUETOOTH_DEFAULT_TIMEOUT = 30

CONFIG_FLOW_BLUETOOTH_TIMEOUT = 60
CONFIG_FLOW_CONNECT_RETRIES = 3
CONFIG_FLOW_CONNECT_RETRY_DELAY = 5

SOLEM_API_MOCK = "solem_api_mock"
DEFAULT_MANUAL_DURATION = 10
