"""Constants for the Solem BL-IP integration."""

DOMAIN = "solem_blip"
V5_SERVICE_UUID = "108b0001-eab5-bc09-d0ea-0b8f467ce8ee"

DEFAULT_SCAN_INTERVAL = 60
MIN_SCAN_INTERVAL = 10
MAX_SCAN_INTERVAL = 3600

CONTROLLER_MAC_ADDRESS = "controller_mac_address"
NUM_STATIONS = "num_stations"
MIN_NUM_STATIONS = 1
MAX_NUM_STATIONS = 8

BLUETOOTH_TIMEOUT = "bluetooth_timeout"
BLUETOOTH_MIN_TIMEOUT = 5
BLUETOOTH_DEFAULT_TIMEOUT = 30
BLUETOOTH_MAX_TIMEOUT = 300

CONFIG_FLOW_BLUETOOTH_TIMEOUT = 60
CONFIG_FLOW_CONNECT_RETRIES = 3
CONFIG_FLOW_CONNECT_RETRY_DELAY = 5

METADATA_READ_TIMEOUT = 5
METADATA_RETRY_INTERVAL = 15 * 60

IRRIGATION_CONFIG_READ_TIMEOUT = 30
IRRIGATION_CONFIG_RETRY_INTERVAL = 15 * 60
IRRIGATION_CONFIG_REFRESH_INTERVAL = 60 * 60
IRRIGATION_CONFIG_UPDATE_INTERVAL = 15 * 60

PROGRAM_LABELS = ("A", "B", "C")

SET_TIME_MIN_INTERVAL = 24 * 60 * 60

SOLEM_API_MOCK = "solem_api_mock"
DEFAULT_MANUAL_DURATION = 10
