"""Confirmed onboard controller-name labeling for entry title and device.

The name comes from the optional V5 identification name record read by
the BLE library during the firmware identification read
(``FirmwareVersion["controller_name"]``). This module applies a
confirmed name to integration-owned labels only:

- the config entry data record (``controller_name``) so offline startup
  labels correctly without a BLE connection,
- the config entry title, and only when it is still auto-generated
  (previous onboard name, MAC, or the generic "Solem BL-IP"),
- the device registry name, never a user rename (``name_by_user``) or
  an entity override.

Read-only by design: no rename command is sent to the controller and
the BLE advertised name is never corrected.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from homeassistant.helpers import device_registry as dr

from .const import CONTROLLER_MAC_ADDRESS, CONTROLLER_NAME, DOMAIN

if TYPE_CHECKING:
    from .coordinator import SolemCoordinator

# Titles that may be replaced by the confirmed onboard name. Anything
# else is treated as user-authored and is never touched.
_AUTO_TITLE_FALLBACKS = ("Solem BL-IP",)


def _is_auto_title(coordinator: SolemCoordinator, title: str) -> bool:
    """Return True when an entry title was generated by this integration."""
    entry = coordinator.config_entry
    if entry is None:
        return False
    if title in _AUTO_TITLE_FALLBACKS:
        return True
    if title == entry.data.get(CONTROLLER_MAC_ADDRESS):
        return True
    return bool(
        coordinator.controller_name and title == coordinator.controller_name
    )


def apply_controller_name(coordinator: SolemCoordinator, name: str) -> None:
    """Persist an onboard name and update only HA's integration-owned labels."""
    entry = coordinator.config_entry
    previous = coordinator.controller_name
    coordinator.controller_name = name
    if entry is not None and entry.data.get(CONTROLLER_NAME) != name:
        auto_titles = {
            previous,
            coordinator.controller_mac_address,
        }
        auto_titles.update(_AUTO_TITLE_FALLBACKS)
        auto_titles.discard(None)
        coordinator.hass.config_entries.async_update_entry(
            entry,
            data={**entry.data, CONTROLLER_NAME: name},
            title=(
                name
                if entry.title in auto_titles or _is_auto_title(coordinator, entry.title)
                else entry.title
            ),
        )
    registry = dr.async_get(coordinator.hass)
    device = None
    if entry is not None:
        try:
            device = registry.async_get_device_by_identifier(
                (DOMAIN, coordinator.controller_mac_address),
                config_entry_id=entry.entry_id,
            )
        except (TypeError, ValueError):
            # A malformed cached address must never break the poll cycle.
            device = None
    if device is not None and device.name != name:
        registry.async_update_device(device.id, name=name)
